name: "Beta stage - From ALPHA to BETA"

on:
  workflow_dispatch:
    inputs:
      version_for_beta_channel:
        description: 'Version of ALPHA app in format {major}-{minor}-{patch}-{releaseAutoIncrement}'
        required: true

env:
  APP_GCS_FOLDER: hubis-app

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2204

    steps:
      ##############################################################################################
      #     SETUP
      ##############################################################################################

      # TODO - Validate version_for_beta_channel input!

      - name: Sourcecode checkout
        uses: actions/checkout@v3

      ##############################################################################################
      #     CHECK CURRENT STAGE STATUS
      ##############################################################################################

      - name: Get Google Cloud Platform access
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: 'ocff-infra-artifacts-v1'
          service_account_key: ${{ secrets.GOOGLE_BUCKET_CREDENTIALS }}
          export_default_credentials: true

      - name: Check that ALPHA stage is set (Google Cloud Storage)
        run: ./.github/workflows/scripts/stageExistsCheck.sh ${{ github.event.inputs.version_for_beta_channel }} alpha $APP_GCS_FOLDER
        shell: bash

      - name: Check that no BETA stage is set (Google Cloud Storage)
        run: ./.github/workflows/scripts/stageDoesntExistsCheck.sh ${{ github.event.inputs.version_for_beta_channel }} beta $APP_GCS_FOLDER
        shell: bash

      - name: Check that no GA stage is set (Google Cloud Storage)
        run: ./.github/workflows/scripts/stageDoesntExistsCheck.sh ${{ github.event.inputs.version_for_beta_channel }} ga $APP_GCS_FOLDER
        shell: bash

      ##############################################################################################
      #     MOVE FROM ALPHA TO BETA STAGE
      ##############################################################################################

      - name: Move app from ALPHA to BETA stage (Google Cloud Storage)
        run: gcloud storage cp -r gs://ocff-deployment-mobileapps/$APP_GCS_FOLDER/releases/${{ github.event.inputs.version_for_beta_channel }}/alpha gs://ocff-deployment-mobileapps/$APP_GCS_FOLDER/releases/${{ github.event.inputs.version_for_beta_channel }}/beta

      # TODO - MOVE TO TOP!
      - name: Upload Android App Bundle (*.aab) to Google Play (BETA track)
        uses: r0adkll/upload-google-play@8c2ebfdb6e1b439d3a31d35772b3f0f489d688c9
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          packageName: com.ocfulfillment.fulfillmentapp
          releaseFiles: ./app/build/outputs/bundle/release/fft_${{ env.APP_VERSION }}_${{ env.BRANCH_TYPE }}-release.aab
          releaseName: fulfillmenttools ${{ fromJson(steps.version.outputs.content).versionCode }} (${{ fromJson(steps.version.outputs.content).major }}.${{ fromJson(steps.version.outputs.content).minor }}.${{ fromJson(steps.version.outputs.content).patch }})
          track: beta
          status: completed
          mappingFile: ./app/build/outputs/mapping/release/mapping.txt
