name: "Beta stage - From alpha to BETA"

on:
  workflow_dispatch:
    inputs:
      version_for_beta_channel:
        description: 'Version of ALPHA app in format {major}-{minor}-{patch}-{build_nr}'
        required: true

env:
  APP_GCS_FOLDER: hubis-app

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2204

    steps:
      ##############################################################################################
      #     SETUP
      ##############################################################################################

      - name: Sourcecode checkout
        uses: actions/checkout@v3

      ##############################################################################################
      #     CHECK CURRENT STAGE STATUS
      ##############################################################################################

      - name: Get Google Cloud Platform access
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: 'ocff-infra-artifacts-v1'
          service_account_key: ${{ secrets.GOOGLE_BUCKET_CREDENTIALS }}
          export_default_credentials: true

      - name: Check that ALPHA stage is set (Google Cloud Storage)
        run: ./.github/workflows/scripts/stageExistsCheck.sh ${{ github.event.inputs.version_for_beta_channel }} alpha $APP_GCS_FOLDER
        shell: bash

      - name: Check that no BETA stage is set (Google Cloud Storage)
        run: ./.github/workflows/scripts/stageDoesntExistsCheck.sh ${{ github.event.inputs.version_for_beta_channel }} beta $APP_GCS_FOLDER
        shell: bash

      - name: Check that no GA stage is set (Google Cloud Storage)
        run: ./.github/workflows/scripts/stageDoesntExistsCheck.sh ${{ github.event.inputs.version_for_beta_channel }} ga $APP_GCS_FOLDER
        shell: bash

      ##############################################################################################
      #     UPDATE GIT RELEASE TO BETA
      ##############################################################################################

      - name: Update GitHub release v${{ github.event.inputs.version_for_beta_channel }} to BETA
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.event.inputs.version_for_beta_channel }} [BETA]
          tag_name: v${{ github.event.inputs.version_for_beta_channel }}
          draft: false
          prerelease: false

      ##############################################################################################
      #     MOVE FROM ALPHA TO BETA STAGE
      ##############################################################################################

      - name: Move app from ALPHA to BETA stage (Google Cloud Storage)
        run: gcloud storage cp -r gs://ocff-deployment-mobileapps/$APP_GCS_FOLDER/releases/${{ github.event.inputs.version_for_beta_channel }}/alpha gs://ocff-deployment-mobileapps/$APP_GCS_FOLDER/releases/${{ github.event.inputs.version_for_beta_channel }}/beta
