name: "Beta stage - From alpha to beta"

on:
  workflow_dispatch:
    inputs:
      version_for_beta_channel:
        description: 'Version of alpha app in format {major}-{minor}-{patch}-{build_nr}'
        required: true

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2204

    steps:
      - name: Sourcecode Checkout
        uses: actions/checkout@v3

      - name: Get Google Cloud Platform access
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: 'ocff-infra-artifacts-v1'
          service_account_key: ${{ secrets.GOOGLE_BUCKET_CREDENTIALS }}
          export_default_credentials: true

      - name: Check that alpha stage is set (Google Cloud Storage)
        run: ./.github/workflows/scripts/stageExistsCheck.sh ${{ github.event.inputs.version_for_beta_channel }} alpha hubis-app
        shell: bash

      - name: Check that no beta stage is set (Google Cloud Storage)
        run: ./.github/workflows/scripts/stageDoesntExistsCheck.sh ${{ github.event.inputs.version_for_beta_channel }} beta hubis-app
        shell: bash

      - name: Check that no GA stage is set (Google Cloud Storage)
        run: ./.github/workflows/scripts/stageDoesntExistsCheck.sh ${{ github.event.inputs.version_for_beta_channel }} ga hubis-app
        shell: bash

      - name: Move app from alpha to beta stage (Google Cloud Storage)
        run: gcloud storage cp -r gs://ocff-deployment-mobileapps/hubis-app/releases/${{ github.event.inputs.version_for_beta_channel }}/alpha gs://ocff-deployment-mobileapps/hubis-app/releases/${{ github.event.inputs.version_for_beta_channel }}/beta
