name: "Build & Deploy Alpha Release"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2004

    steps:
      - name: Print Branch Name
        run: |
          echo The branch are ${{ github.ref }}

      - name: Check current branch is a release branch.
        if: ${{ startsWith(github.ref, 'refs/heads/release') }}
        run: |
          echo SUCCESS: The branch ${{ github.ref }} is a release branch.

      - name: Cancel Build If Current Branch Is No Release Branch.
        if: ${{ !startsWith(github.ref, 'refs/heads/release') }}
        run: |
          echo ERROR: The branch ${{ github.ref }} is no release branch.
          exit 1

      - name: Sourcecode Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Execute Unit Tests
        run: bash ./gradlew testReleaseUnitTest --stacktrace

      - name: Save Unit Tests Result
        uses: actions/upload-artifact@v3
        with:
          name: testReleaseResult
          path: app/build/reports/tests/testReleaseUnitTest
