# Comment

name: "Build & deploy alpha release"

on:
  workflow_dispatch:
    inputs:
      release_branch_name:
        description: 'Release branch name'
        required: true
        type: string

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2004

    steps:
      - name: Print Release Branch Name
        run: |
          echo The release branch are ${{ inputs.release_branch_name }}

      - name: Sourcecode Checkout
        uses: actions/checkout@v3
