name: "Build & Deploy Alpha Release"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2004

    steps:
      - name: Check current branch is a release branch.
        if: ${{ startsWith(github.ref, 'refs/heads/release') }}
        run: |
          echo SUCCESS: The branch ${{ github.ref }} is a release branch.

      - name: Cancel Build If Current Branch Is No Release Branch.
        if: ${{ !startsWith(github.ref, 'refs/heads/release') }}
        run: |
          echo ERROR: The branch ${{ github.ref }} is no release branch.
          exit 1

      - name: Sourcecode Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Execute Unit Tests
        run: bash ./gradlew testReleaseUnitTest --stacktrace

      #      - name: Display Unit Tests Result
      #        uses: dorny/test-reporter@v1
      #        if: success() || failure()
      #        with:
      #          name: Unit Tests
      #          path: app/build/test-results/testReleaseUnitTest/jest-*.xml
      #          reporter: jest-junit

      - name: Build Universal APK (release)
        id: buildAPKRelease
        run: |
          bash ./gradlew packageReleaseUniversalApk --stacktrace
          #env:
          #BRANCH_TYPE: ${{ env.BRANCH_TYPE }}
          #STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        #KEY_PASSWORD_RELEASE: ${{ secrets.KEY_PASSWORD_RELEASE }}

      - name: Get Google Cloud Platform Access
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'ocff-infra-artifacts-v1'
          service_account_key: ${{ secrets.GOOGLE_BUCKET_CREDENTIALS }}
          export_default_credentials: true

      - name: Read Version From JSON
        id: version
        uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b
        with:
          path: ./buildSrc/version.json

      - name: Write Env-Parameter
        run: |
          echo "MAJOR=${{ fromJson(steps.version.outputs.content).major }}" >> $GITHUB_ENV
          echo "MINOR=${{ fromJson(steps.version.outputs.content).minor }}" >> $GITHUB_ENV
          echo "PATCH=${{ fromJson(steps.version.outputs.content).patch }}" >> $GITHUB_ENV
          echo "VERSION_CODE=${{ fromJson(steps.version.outputs.content).versionCode }}" >> $GITHUB_ENV
          echo The branch are ${{ env.MAJOR }}-${{ env.MINOR }}-${{ env.PATCH }}-${{ github.run_number }}
