# Comment

name: "Build & deploy alpha release"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2004

    steps:
      - name: Print Branch Name
        run: |
          echo The branch are ${{ github.repository }}
          echo The branch are ${{ github.ref }}

      - name: If Statement
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo The branch are ${{ github.repository }}

      - name: Sourcecode Checkout
        uses: actions/checkout@v3
