# Comment

name: "Build & deploy alpha release"

on:
  workflow_dispatch:

jobs:
  build:
    name: Execute Steps...
    runs-on: buildjet-8vcpu-ubuntu-2004

    steps:
      - name: Print Branch Name
        run: |
          echo The branch are ${github.repository}

      - name: Print Branch Name
        if: startsWith(${GITHUB_HEAD_REF}, "refs/heads/release/")

      - name: Sourcecode Checkout
        uses: actions/checkout@v3
