# Comment

name: "Build & deploy alpha release"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2004

    steps:
      - name: Print Branch Name
        run: |
          echo The branch are ${{ github.ref }}

      - name: Check current branch is a release branch.
        if: ${{ !startsWith(github.ref, 'refs/heads/release') }}
        run: |
          echo ERROR: The branch ${{ github.ref }} is no release branch.
          exit 1

      - name: Sourcecode Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK 11
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Execute Unit Tests
        run: bash ./gradlew testReleaseUnitTest --stacktrace
