# Comment

name: "Build & deploy alpha release"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: buildjet-8vcpu-ubuntu-2004

    steps:
      - name: Print Branch Name
        run: |
          echo The branch are ${GITHUB_REF}
          echo The branch are ${GITHUB_HEAD_REF}

      - name: Sourcecode Checkout
        uses: actions/checkout@v3

